<a href="https://colab.research.google.com/github/Laura-Tovo/EP-2--Luli-e-Laura/blob/main/AI_Ubiquity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Social Network

In [1]:
import numpy as np #for arrays
import pandas as pd #to manage and import datasets
import matplotlib.pyplot as plt #plotting

In [5]:
dataset2 = pd.read_csv("Social_Network_Ads.csv")
X = dataset2.iloc[:,:-1].values # todos os valores de toda colunas menos a última
Y = dataset2.iloc[:,-1].values # só os valores da ultima coluna
dataset2

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,3])
X[:,3] = imputer.transform(X[:,3])

ValueError: Expected 2D array, got 1D array instead:
array=[ 19000.  20000.  43000.  57000.  76000.  58000.  84000. 150000.  33000.
  65000.  80000.  52000.  86000.  18000.  82000.  80000.  25000.  26000.
  28000.  29000.  22000.  49000.  41000.  22000.  23000.  20000.  28000.
  30000.  43000.  18000.  74000. 137000.  16000.  44000.  90000.  27000.
  28000.  49000.  72000.  31000.  17000.  51000. 108000.  15000.  84000.
  20000.  79000.  54000. 135000.  89000.  32000.  44000.  83000.  23000.
  58000.  55000.  48000.  79000.  18000. 117000.  20000.  87000.  66000.
 120000.  83000.  58000.  19000.  82000.  63000.  68000.  80000.  27000.
  23000. 113000.  18000. 112000.  52000.  27000.  87000.  17000.  80000.
  42000.  49000.  88000.  62000. 118000.  55000.  85000.  81000.  50000.
  81000. 116000.  15000.  28000.  83000.  44000.  25000. 123000.  73000.
  37000.  88000.  59000.  86000. 149000.  21000.  72000.  35000.  89000.
  86000.  80000.  71000.  71000.  61000.  55000.  80000.  57000.  75000.
  52000.  59000.  59000.  75000.  72000.  75000.  53000.  51000.  61000.
  65000.  32000.  17000.  84000.  58000.  31000.  87000.  68000.  55000.
  63000.  82000. 107000.  59000.  25000.  85000.  68000.  59000.  89000.
  25000.  89000.  96000.  30000.  61000.  74000.  15000.  45000.  76000.
  50000.  47000.  15000.  59000.  75000.  30000. 135000. 100000.  90000.
  33000.  38000.  69000.  86000.  55000.  71000. 148000.  47000.  88000.
 115000. 118000.  43000.  72000.  28000.  47000.  22000.  23000.  34000.
  16000.  71000. 117000.  43000.  60000.  66000.  82000.  41000.  72000.
  32000.  84000.  26000.  43000.  70000.  89000.  43000.  79000.  36000.
  80000.  22000.  39000.  74000. 134000.  71000. 101000.  47000. 130000.
 114000. 142000.  22000.  96000. 150000.  42000.  58000.  43000. 108000.
  65000.  78000.  96000. 143000.  80000.  91000. 144000. 102000.  60000.
  53000. 126000. 133000.  72000.  80000. 147000.  42000. 107000.  86000.
 112000.  79000.  57000.  80000.  82000. 143000. 149000.  59000.  88000.
 104000.  72000. 146000.  50000. 122000.  52000.  97000.  39000.  52000.
 134000. 146000.  44000.  90000.  72000.  57000.  95000. 131000.  77000.
 144000. 125000.  72000.  90000. 108000.  75000.  74000. 144000.  61000.
 133000.  76000.  42000. 106000.  26000.  74000.  71000.  88000.  38000.
  36000.  88000.  61000.  70000.  21000. 141000.  93000.  62000. 138000.
  79000.  78000. 134000.  89000.  39000.  77000.  57000.  63000.  73000.
 112000.  79000. 117000.  38000.  74000. 137000.  79000.  60000.  54000.
 134000. 113000. 125000.  50000.  70000.  96000.  50000. 141000.  79000.
  75000. 104000.  55000.  32000.  60000. 138000.  82000.  52000.  30000.
 131000.  60000.  72000.  75000. 118000. 107000.  51000. 119000.  65000.
  65000.  60000.  54000. 144000.  79000.  55000. 122000. 104000.  75000.
  65000.  51000. 105000.  63000.  72000. 108000.  77000.  61000. 113000.
  75000.  90000.  57000.  99000.  34000.  70000.  72000.  71000.  54000.
 129000.  34000.  50000.  79000. 104000.  29000.  47000.  88000.  71000.
  26000.  46000.  83000.  73000. 130000.  80000.  32000.  74000.  53000.
  87000.  23000.  64000.  33000. 139000.  28000.  33000.  60000.  39000.
  71000.  34000.  35000.  33000.  23000.  45000.  42000.  59000.  41000.
  23000.  20000.  33000.  36000.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [6]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,Y_train)

NameError: name 'X_train' is not defined

# Data

In [ ]:
#import the libraries
import numpy as np #for arrays
import pandas as pd #to manage and import datasets
import matplotlib.pyplot as plt #plotting

In [ ]:
dataset = pd.read_csv("Data.csv")
X = dataset.iloc[:,:-1].values # todos os valores de toda colunas menos a última
Y = dataset.iloc[:,-1].values # só os valores da ultima coluna
dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3]) #the 3 is not taken into consideration [:,[1,2]] is also applicabel
X[:,1:3] = imputer.transform(X[:,1:3])

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

In [ ]:
X, Y

(array([['France', 44.0, 72000.0],
        ['Spain', 27.0, 48000.0],
        ['Germany', 30.0, 54000.0],
        ['Spain', 38.0, 61000.0],
        ['Germany', 40.0, 63777.77777777778],
        ['France', 35.0, 58000.0],
        ['Spain', 38.77777777777778, 52000.0],
        ['France', 48.0, 79000.0],
        ['Germany', 50.0, 83000.0],
        ['France', 37.0, 67000.0]], dtype=object),
 array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1]))

In [ ]:
#dummy encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('country', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X), dtype=np.float64)
X

array([[1.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 4.400000e+01,
                 inf],
       [0.000000e+00, 1.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 0.000000e+00, 1.000000e+00, 2.700000e+01,
        4.800000e+04],
       [0.000000e+00, 1.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 1.000000e+00, 0.000000e+00, 3.000000e+01,
        5.401600e+04],
       [0.000000e+00, 1.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 0.000000e+00, 1.000000e+00, 3.800000e+01,
        6.099200e+04],
       [0.000000e+00, 1.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 1.000000e+00, 0.000000e+00, 4.000000e+01,
        6.377600e+04],
       [1.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 3.500000e+01,
        5.798400e+04],
       [0.000000e+00, 1.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 0.000000e+00, 1.000000e+00, 3.878125e+01,
        5.200000e+04],
       [1.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 4.800000e+01,
                 inf],
       [0.000000e+00, 1.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 1.000000e+00, 0.000000e+00, 5.000000e+01,
                 inf],
       [1.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 3.700000e+01,
                 inf]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [ ]:
X_train

array([[ 1.        , -1.        ,  2.64575131, -0.77459667,  0.26306757,
         0.12381479],
       [-1.        ,  1.        , -0.37796447, -0.77459667, -0.25350148,
         0.46175632],
       [ 1.        , -1.        , -0.37796447,  1.29099445, -1.97539832,
        -1.53093341],
       [ 1.        , -1.        , -0.37796447,  1.29099445,  0.05261351,
        -1.11141978],
       [-1.        ,  1.        , -0.37796447, -0.77459667,  1.64058505,
         1.7202972 ],
       [ 1.        , -1.        , -0.37796447,  1.29099445, -0.0813118 ,
        -0.16751412],
       [-1.        ,  1.        , -0.37796447, -0.77459667,  0.95182631,
         0.98614835],
       [-1.        ,  1.        , -0.37796447, -0.77459667, -0.59788085,
        -0.48214934]])

# Salaries

In [26]:
import numpy as np #for arrays
import pandas as pd #to manage and import datasets
import matplotlib.pyplot as plt #plotting

In [27]:
salaries = pd.read_csv("Salaries.csv")
X_s = salaries.iloc[:,:-1].values # todos os valores de toda colunas menos a última
Y_s = salaries.iloc[:,-1].values # só os valores da ultima coluna
salaries.head(5)

<ipython-input-27-c8b8674a0660>:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  salaries = pd.read_csv("Salaries.csv")

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [28]:
salaries.describe()

                  Id       TotalPay  TotalPayBenefits           Year  Notes
count  148654.000000  148654.000000     148654.000000  148654.000000    0.0
mean    74327.500000   74768.321972      93692.554811    2012.522643    NaN
std     42912.857795   50517.005274      62793.533483       1.117538    NaN
min         1.000000    -618.130000       -618.130000    2011.000000    NaN
25%     37164.250000   36168.995000      44065.650000    2012.000000    NaN
50%     74327.500000   71426.610000      92404.090000    2013.000000    NaN
75%    111490.750000  105839.135000     132876.450000    2014.000000    NaN
max    148654.000000  567595.430000     567595.430000    2014.000000    NaN

# Pokemon

In [84]:
import numpy as np #for arrays
import pandas as pd #to manage and import datasets
import matplotlib.pyplot as plt #plotting

In [85]:
pokemon = pd.read_csv("pokemon.csv")
X_p = pokemon.iloc[:,:-1].values # todos os valores de toda colunas menos a última
Y_p = pokemon.iloc[:,-1].values # só os valores da ultima coluna
pokemon.head(10)

,Number,Name,Type_1,Type_2,Total,HP,Attack,Defense,Sp_Atk,Sp_Def,...,Color,hasGender,Pr_Male,Egg_Group_1,Egg_Group_2,hasMegaEvolution,Height_m,Weight_kg,Catch_Rate,Body_Style
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,...,Green,True,0.875,Monster,Grass,False,0.71,6.9,45,quadruped
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,...,Green,True,0.875,Monster,Grass,False,0.99,13.0,45,quadruped
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,...,Green,True,0.875,Monster,Grass,True,2.01,100.0,45,quadruped
3,4,Charmander,Fire,NaN,309,39,52,43,60,50,...,Red,True,0.875,Monster,Dragon,False,0.61,8.5,45,bipedal_tailed
4,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,...,Red,True,0.875,Monster,Dragon,False,1.09,19.0,45,bipedal_tailed
5,6,Charizard,Fire,Flying,534,78,84,78,109,85,...,Red,True,0.875,Monster,Dragon,True,1.70,90.5,45,bipedal_tailed
6,7,Squirtle,Water,NaN,314,44,48,65,50,64,...,Blue,True,0.875,Monster,Water_1,False,0.51,9.0,45,bipedal_tailed
7,8,Wartortle,Water,NaN,405,59,63,80,65,80,...,Blue,True,0.875,Monster,Water_1,False,0.99,22.5,45,bipedal_tailed
8,9,Blastoise,Water,NaN,530,79,83,100,85,105,...,Blue,True,0.875,Monster,Water_1,True,1.60,85.5,45,bipedal_tailed
9,10,Caterpie,Bug,NaN,195,45,30,35,20,20,...,Green,True,0.500,Bug,NaN,False,0.30,2.9,255,insectoid

In [86]:
pokemon.columns

Index(['Number', 'Name', 'Type_1', 'Type_2', 'Total', 'HP', 'Attack',
       'Defense', 'Sp_Atk', 'Sp_Def', 'Speed', 'Generation', 'isLegendary',
       'Color', 'hasGender', 'Pr_Male', 'Egg_Group_1', 'Egg_Group_2',
       'hasMegaEvolution', 'Height_m', 'Weight_kg', 'Catch_Rate',
       'Body_Style'],
      dtype='object')

In [87]:
pokemon.describe()

,Number,Total,HP,Attack,Defense,Sp_Atk,Sp_Def,Speed,Generation,Pr_Male,Height_m,Weight_kg,Catch_Rate
count,721.00000,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000,644.000000,721.000000,721.000000,721.000000
mean,361.00000,417.945908,68.380028,75.013870,70.808599,68.737864,69.291262,65.714286,3.323162,0.553377,1.144979,56.773370,100.246879
std,208.27906,109.663671,25.848272,28.984475,29.296558,28.788005,27.015860,27.277920,1.669873,0.199969,1.044369,89.095667,76.573513
min,1.00000,180.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.000000,0.000000,0.100000,0.100000,3.000000
25%,181.00000,320.000000,50.000000,53.000000,50.000000,45.000000,50.000000,45.000000,2.000000,0.500000,0.610000,9.400000,45.000000
50%,361.00000,424.000000,65.000000,74.000000,65.000000,65.000000,65.000000,65.000000,3.000000,0.500000,0.990000,28.000000,65.000000
75%,541.00000,499.000000,80.000000,95.000000,85.000000,90.000000,85.000000,85.000000,5.000000,0.500000,1.400000,61.000000,180.000000
max,721.00000,720.000000,255.000000,165.000000,230.000000,154.000000,230.000000,160.000000,6.000000,1.000000,14.500000,950.000000,255.000000

In [88]:
pokemon_sorted = pokemon.sort_values(by='Attack', ascending=False)
pokemon_sorted

,Number,Name,Type_1,Type_2,Total,HP,Attack,Defense,Sp_Atk,Sp_Def,...,Color,hasGender,Pr_Male,Egg_Group_1,Egg_Group_2,hasMegaEvolution,Height_m,Weight_kg,Catch_Rate,Body_Style
408,409,Rampardos,Rock,NaN,495,97,165,60,65,50,...,Blue,True,0.875,Monster,NaN,False,1.60,102.5,45,bipedal_tailed
288,289,Slaking,Normal,NaN,670,150,160,100,95,65,...,Brown,True,0.500,Field,NaN,False,2.01,130.5,45,bipedal_tailless
485,486,Regigigas,Normal,NaN,670,110,160,110,80,110,...,White,False,NaN,Undiscovered,NaN,False,3.71,420.0,3,bipedal_tailless
643,644,Zekrom,Dragon,Electric,680,100,150,120,120,100,...,Black,False,NaN,Undiscovered,NaN,False,2.90,345.0,3,bipedal_tailed
382,383,Groudon,Ground,NaN,670,100,150,140,100,90,...,Red,False,NaN,Undiscovered,NaN,False,3.51,950.0,3,bipedal_tailed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,129,Magikarp,Water,NaN,200,20,10,55,15,20,...,Red,True,0.500,Water_2,Dragon,False,0.89,10.0,255,with_fins
212,213,Shuckle,Bug,Rock,505,20,10,230,10,230,...,Yellow,True,0.500,Bug,NaN,False,0.61,20.5,190,insectoid
241,242,Blissey,Normal,NaN,540,255,10,10,75,135,...,Pink,True,0.000,Fairy,NaN,False,1.50,46.8,30,bipedal_tailless
112,113,Chansey,Normal,NaN,450,250,5,5,35,105,...,Pink,True,0.000,Fairy,NaN,False,1.09,34.6,30,bipedal_tailed
439,440,Happiny,Normal,NaN,220,100,5,5,15,65,...,Pink,True,0.000,Undiscovered,NaN,False,0.61,24.4,130,bipedal_tailless

In [89]:
pokemon["Defense"].describe()

count    721.000000
mean      70.808599
std       29.296558
min        5.000000
25%       50.000000
50%       65.000000
75%       85.000000
max      230.000000
Name: Defense, dtype: float64

In [90]:
print(pokemon["Total"].mean())
print(pokemon["Total"].median())
print(pokemon["Total"].max())
print(pokemon["Total"].min())

417.94590846047157
424.0
720
180

In [91]:
pokemon["Type_1"].mode()

0    Water
Name: Type_1, dtype: object

In [92]:
print(pokemon.isnull().sum())

Number                0
Name                  0
Type_1                0
Type_2              371
Total                 0
HP                    0
Attack                0
Defense               0
Sp_Atk                0
Sp_Def                0
Speed                 0
Generation            0
isLegendary           0
Color                 0
hasGender             0
Pr_Male              77
Egg_Group_1           0
Egg_Group_2         530
hasMegaEvolution      0
Height_m              0
Weight_kg             0
Catch_Rate            0
Body_Style            0
dtype: int64

In [93]:
pokemon2 = pokemon

In [94]:
pokemon2= pokemon2.drop('Type_2', axis=1)
pokemon2= pokemon2.drop('Egg_Group_2', axis=1)

In [95]:
X_p2 = pokemon2.iloc[:,:-1].values # todos os valores de toda colunas menos a última
Y_p2 = pokemon2.iloc[:,-1].values # só os valores da ultima coluna
pokemon2.head(2)

,Number,Name,Type_1,Total,HP,Attack,Defense,Sp_Atk,Sp_Def,Speed,...,isLegendary,Color,hasGender,Pr_Male,Egg_Group_1,hasMegaEvolution,Height_m,Weight_kg,Catch_Rate,Body_Style
0,1,Bulbasaur,Grass,318,45,49,49,65,65,45,...,False,Green,True,0.875,Monster,False,0.71,6.9,45,quadruped
1,2,Ivysaur,Grass,405,60,62,63,80,80,60,...,False,Green,True,0.875,Monster,False,0.99,13.0,45,quadruped

In [101]:
pokemon2.columns

Index(['Number', 'Name', 'Type_1', 'Total', 'HP', 'Attack', 'Defense',
       'Sp_Atk', 'Sp_Def', 'Speed', 'Generation', 'isLegendary', 'Color',
       'hasGender', 'Pr_Male', 'Egg_Group_1', 'hasMegaEvolution', 'Height_m',
       'Weight_kg', 'Catch_Rate', 'Body_Style'],
      dtype='object')

In [117]:
pokemon2 = pokemon2.dropna()

In [120]:
print(pokemon2.isnull().sum())

Number              0
Name                0
Type_1              0
Total               0
HP                  0
Attack              0
Defense             0
Sp_Atk              0
Sp_Def              0
Speed               0
Generation          0
isLegendary         0
Color               0
hasGender           0
Pr_Male             0
Egg_Group_1         0
hasMegaEvolution    0
Height_m            0
Weight_kg           0
Catch_Rate          0
Body_Style          0
dtype: int64